### ISSUE TITLE
Images not found in Bonita BPM Studio installation

### ISSUE THREAD

**Issue by NathalieC** [bonitasoft/bonita-documentation-site#76] opened 2021-02-10 14:33 UTC
![image](https://user-images.githubusercontent.com/10465851/107523883-7ddfbe80-6bb5-11eb-9dde-19bf872d3acf.png)

We should access: 
image:bonita/images/${varVersion}/studio_welcome_page_ko.png[,850px]
and
image:bonita/images/${varVersion}/studio_welcome_page_ok.png[,850px]

------
In bonita-bpm-portal-interface-overview, we access 
image:images/images-6_0/admin_view7.1.png[]
// {.img-responsive}
And it works fine.

### Tasks

Update bonita-doc versions
- [x] 7.5
- [x] 7.6
- [x] 7.7
- [x] 7.8
- [x] 7.9+ see https://github.com/bonitasoft/bonita-documentation-site/issues/76#issuecomment-782152228
- [x] ensure the changes have been deployed to production

**Comment by tbouffard** [comment] 2021-02-10 15:47
The issue here is that instead of using relative path to image, the markdown source defined the link with html markup (probably to set the image width)
`<img src="bonita/images/${varVersion}/studio_welcome_page_ko.png" width="850px"/>`

The converted asciidoctor still contains this wrong path `image:bonita/images/${varVersion}/studio_welcome_page_ko.png[,850px]`
This should be instead something like `image:images/studio_welcome_page_ko.png[,850px]`

To be investigated and documented in the conversion guide if confirmed

**Comment by tbouffard** [comment] 2021-02-19 15:38
the issue is on the 7.5 documentation, so images must be kept, we are not going to rework the content, just make the images display

**Comment by alachambre** [comment] 2021-02-19 15:46
Well I reworked the content on the 7.9 branch, it had to be done -> https://github.com/bonitasoft/bonita-doc/pull/1420

for the old version yes you right we have to fix the references of the images.

**Comment by tbouffard** [comment] 2021-03-01 18:42
Fixed in 7.5: https://preview.documentation.bonitasoft.com/bonita/7.5/bonita-bpm-studio-installation

![image](https://user-images.githubusercontent.com/27200110/109543150-44201a80-7ac6-11eb-875a-89e7f0a6f79f.png)

**Comment by tbouffard** [comment] 2021-03-10 16:33
All versions have been fixed

**Closed by tbouffard** 2021-03-10 16:33 UTC
Labels: First Iteration, preview-feedback :eyes:
